#!/usr/bin/perl
#
# This code is distributed under the terms of the GPL
#
# (c) 2005 marco.s
#
# $Id: install-calamaris-ipcop,v 1.0 2005/12/02 00:00:00 marco.s Exp $
#

$scriptpath=substr($0,0,rindex($0,"/"));
$swroot="/var/ipcop";
$plroot="/var/ipcop";
$cgibin="/home/httpd/cgi-bin";
$apdir="/var/ipcop/proxy/calamaris";

$i=1;

print "\n=====================================================\n";
print "  IPCop 2.0.6 Calamaris Proxy Report add-on uninstall\n";
print "=====================================================\n\n";

if (!-e "$plroot/header.pl") { die "ERROR: This system is not running IPCop.\n\n"; }

if ((!-e "$cgibin/calamaris.cgi") || (!-d "$apdir")) { die "ERROR: Calamaris Proxy Report add-on is not installed.\n\n"; }

if (!(-e "$plroot/general-functions.pl")) { die "ERROR: This system is not running IPCop 2.0.6 or higher.\n\n"; }


print "Step $i: Removing directories\n";
print "--------------------------------------------\n\n";

print "$apdir\n";
if (-d "$apdir") { system("rm -rf $apdir"); };

print "/var/log/calamaris\n";
if (-d "/var/log/calamaris") { system("rm -rf /var/log/calamaris"); };

print "\n";
$i++;


print "Step $i: Removing Calamaris files\n";
print "--------------------------------------------\n\n";

print "$cgibin/calamaris.cgi\n";
system("rm $cgibin/calamaris.cgi");

print "\n";
$i++;


print "Step $i: Restoring system files\n";
print "--------------------------------------------\n\n";

print "Restoring language files:\n";

foreach $language (<$scriptpath/langs/*>)
{
    
	undef(@calamarisstrings);
	undef(@ipcopstrings);
	$lastslashpos = rindex($language,"/");
	$languagefile = substr($language,$lastslashpos+1);
	print "$swroot/langs/$languagefile\n";
	system("rm -f /var/ipcop/addons/lang/$languagefile";
	
	
	print "\nRebuilding language cache\n";
	system("/usr/local/bin/rebuildlangtexts");

print "\n";

print "\n";
